CREATE PROCEDURE dbo.GRI_LISTAR_NP_AGRUPACION
	 @FEC_INICIO AS DATETIME
	,@FEC_FIN AS DATETIME
	,@NP AS VARCHAR(50) = ''
AS
SET NOCOUNT ON

IF (@NP<>'')
BEGIN

SELECT COD_FABRICA
	,COD_ORDPRO
	,COD_PRESENT
	,COD_FAMITEM
	,MAX(FEC_ULTENTRADA) AS FEC_PRIENTRADA
	,SUM(NUM_ENPROCESO) AS NUM_ENPROCESO
	,SUM(NUM_ENREPROCESOS) AS NUM_ENREPROCESOS
	,COD_PROVEEDOR
	,SUM(NUM_REALIZADAS) AS PROCESADAS
	,DBO.ES_ORDPROCOLTAL_NUM_PREPRO('001', A.COD_ORDPRO, A.COD_PRESENT) AS REQUERIDAS
INTO #PROVEEDORES
FROM CF_ACUMULADO_PROVEEDORES A
WHERE FEC_ULTENTRADA BETWEEN @FEC_INICIO
		AND @FEC_FIN
	AND ES_FACTURABLE = 'N'	
	--CMENDEZ
	AND COD_FAMITEM = 'ES'
GROUP BY COD_FABRICA
	,COD_ORDPRO
	,COD_PRESENT
	,COD_FAMITEM
	,COD_PROVEEDOR
HAVING SUM( NUM_ENPROCESO + NUM_ENREPROCESOS - NUM_AJUSTE ) > 0

/*******************************************************************************************/
SELECT CONVERT(VARCHAR, C.FEC_DESPACHOACT, 103) AS FEC_DESPACHO
	,A.COD_ORDPRO AS NP
	,DES_PRESENT AS COMBO
	,C.COD_ESTPRO AS ESTILO_PROPIO
	,COD_ESTCLI AS ESTILO_CLIENTE
	,NOM_CLIENTE
	,A.COD_FAMITEM
	,DES_FAMITEM
	,NUM_ENPROCESO
	,NUM_ENREPROCESOS
	,CONVERT(VARCHAR, FEC_PRIENTRADA, 103) AS FEC_PRIENTRADA
	,CONVERT(VARCHAR, FEC_FINPROD, 103) AS FECHA_FIN_PRODUCCION
	,DES_PROVEEDOR AS PROVEEDOR
	,A.COD_FABRICA
	,A.COD_PRESENT
	,A.COD_PROVEEDOR
	,PROCESADAS
	,REQUERIDAS
	,REQUERIDAS- PROCESADAS - NUM_ENPROCESO AS POR_INGRESAR
	,DBO.CF_MUESTRA_NRO_APLICACIONES_OP_PROVEEDOR_COMBO_PROCESO(A.COD_ORDPRO, E.COD_PROVEEDOR, F.COD_FAMITEM, A.COD_PRESENT) AS NRO_ARTES
	,DBO.CF_MUESTRA_IMPORTE_APLICACIONES_OP_PROVEEDOR_COMBO_PROCESO(A.COD_ORDPRO, E.COD_PROVEEDOR, F.COD_FAMITEM, A.COD_PRESENT) AS STOCK_VALORIZADO
	,CONVERT(VARCHAR, DBO.PL_FECHA_SUGERIDA_DESPACHO('F', A.COD_ORDPRO), 103) AS FEC_SUGERIDA_DESPACHO
FROM #PROVEEDORES A
	 INNER JOIN ES_ORDPRO C
	 ON A.COD_FABRICA     = C.COD_FABRICA
	AND A.COD_ORDPRO    = C.COD_ORDPRO
     INNER JOIN 	TG_CLIENTE AS D
     ON C.COD_CLIENTE   = D.COD_CLIENTE
	 INNER JOIN  LG_PROVEEDOR AS E
	 ON  A.COD_PROVEEDOR = E.COD_PROVEEDOR
	 INNER JOIN LG_FAMITE AS F
	 ON A.COD_FAMITEM   = F.COD_FAMITEM
	 INNER JOIN ES_ESTPROPRE I
	 ON   C.COD_ESTPRO   = I.COD_ESTPRO
 	 AND A.COD_PRESENT   = I.COD_PRESENT
	 LEFT JOIN PL_ORDENES_A_PROGRAMAR J
	 ON J.COD_TIPORDPRO = 'F'
	 AND A.COD_ORDPRO   = J.COD_ORDPRO
ORDER BY DES_PROVEEDOR
	    ,A.COD_FAMITEM
	    ,NOM_CLIENTE
	    ,COD_ESTCLI
	    ,DES_PRESENT
	    ,A.COD_ORDPRO
	    ,FEC_FINPROD

DROP TABLE #PROVEEDORES

END
--------------------------
--Si se seleciona una NP
--------------------------
ELSE
BEGIN

SELECT COD_FABRICA
	,COD_ORDPRO
	,COD_PRESENT
	,COD_FAMITEM
	,MAX(FEC_ULTENTRADA) AS FEC_PRIENTRADA
	,SUM(NUM_ENPROCESO) AS NUM_ENPROCESO
	,SUM(NUM_ENREPROCESOS) AS NUM_ENREPROCESOS
	,COD_PROVEEDOR
	,SUM(NUM_REALIZADAS) AS PROCESADAS
	,DBO.ES_ORDPROCOLTAL_NUM_PREPRO('001', A.COD_ORDPRO, A.COD_PRESENT) AS REQUERIDAS
INTO #PROVEEDORESNP
FROM CF_ACUMULADO_PROVEEDORES A
WHERE COD_ORDPRO = @NP
	AND ES_FACTURABLE = 'N'	
	--CMENDEZ
	AND COD_FAMITEM = 'ES'
GROUP BY COD_FABRICA
	,COD_ORDPRO
	,COD_PRESENT
	,COD_FAMITEM
	,COD_PROVEEDOR
HAVING SUM( NUM_ENPROCESO + NUM_ENREPROCESOS - NUM_AJUSTE ) > 0

/*******************************************************************************************/
SELECT CONVERT(VARCHAR, C.FEC_DESPACHOACT, 103) AS FEC_DESPACHO
	,A.COD_ORDPRO AS NP
	,DES_PRESENT AS COMBO
	,C.COD_ESTPRO AS ESTILO_PROPIO
	,COD_ESTCLI AS ESTILO_CLIENTE
	,NOM_CLIENTE
	,A.COD_FAMITEM
	,DES_FAMITEM
	,NUM_ENPROCESO
	,NUM_ENREPROCESOS
	,CONVERT(VARCHAR, FEC_PRIENTRADA, 103) AS FEC_PRIENTRADA
	,CONVERT(VARCHAR, FEC_FINPROD, 103) AS FECHA_FIN_PRODUCCION
	,DES_PROVEEDOR AS PROVEEDOR
	,A.COD_FABRICA
	,A.COD_PRESENT
	,A.COD_PROVEEDOR
	,PROCESADAS
	,REQUERIDAS
	,REQUERIDAS- PROCESADAS - NUM_ENPROCESO AS POR_INGRESAR
	,DBO.CF_MUESTRA_NRO_APLICACIONES_OP_PROVEEDOR_COMBO_PROCESO(A.COD_ORDPRO, E.COD_PROVEEDOR, F.COD_FAMITEM, A.COD_PRESENT) AS NRO_ARTES
	,DBO.CF_MUESTRA_IMPORTE_APLICACIONES_OP_PROVEEDOR_COMBO_PROCESO(A.COD_ORDPRO, E.COD_PROVEEDOR, F.COD_FAMITEM, A.COD_PRESENT) AS STOCK_VALORIZADO
	,CONVERT(VARCHAR, DBO.PL_FECHA_SUGERIDA_DESPACHO('F', A.COD_ORDPRO), 103) AS FEC_SUGERIDA_DESPACHO
FROM #PROVEEDORESNP A
	 INNER JOIN ES_ORDPRO C
	 ON A.COD_FABRICA     = C.COD_FABRICA
	AND A.COD_ORDPRO    = C.COD_ORDPRO
     INNER JOIN 	TG_CLIENTE AS D
     ON C.COD_CLIENTE   = D.COD_CLIENTE
	 INNER JOIN  LG_PROVEEDOR AS E
	 ON  A.COD_PROVEEDOR = E.COD_PROVEEDOR
	 INNER JOIN LG_FAMITE AS F
	 ON A.COD_FAMITEM   = F.COD_FAMITEM
	 INNER JOIN ES_ESTPROPRE I
	 ON   C.COD_ESTPRO   = I.COD_ESTPRO
 	 AND A.COD_PRESENT   = I.COD_PRESENT
	 LEFT JOIN PL_ORDENES_A_PROGRAMAR J
	 ON J.COD_TIPORDPRO = 'F'
	 AND A.COD_ORDPRO   = J.COD_ORDPRO
ORDER BY DES_PROVEEDOR
	    ,A.COD_FAMITEM
	    ,NOM_CLIENTE
	    ,COD_ESTCLI
	    ,DES_PRESENT
	    ,A.COD_ORDPRO
	    ,FEC_FINPROD

DROP TABLE #PROVEEDORESNP

END