-- Expandir NP a VARCHAR(100) para soportar NP-Item-Version
ALTER TABLE LIQ_Formulas ALTER COLUMN NP VARCHAR(100);
ALTER TABLE LIQ_FormulaColores ALTER COLUMN NP VARCHAR(100);
ALTER TABLE LIQ_FormulaInsumos ALTER COLUMN NP VARCHAR(100);
ALTER TABLE LIQ_FormulaInsumosPrueba ALTER COLUMN NP VARCHAR(100);
ALTER TABLE LIQ_OperacionesDetalle ALTER COLUMN NP VARCHAR(100);
ALTER TABLE LIQ_MermasStock ALTER COLUMN NPOrigen VARCHAR(100);
ALTER TABLE LIQ_MOV_SolicitudesDetalle ALTER COLUMN NP VARCHAR(100);
-- Si existe LIQ_NP_StockSnapshot
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'LIQ_NP_StockSnapshot')
BEGIN
    ALTER TABLE LIQ_NP_StockSnapshot ALTER COLUMN NP VARCHAR(100);
END
GO

-- Agregar columna Item
IF COL_LENGTH('LIQ_OperacionesDetalle', 'Item') IS NULL
    ALTER TABLE LIQ_OperacionesDetalle ADD Item VARCHAR(100) NOT NULL DEFAULT '0000';
IF COL_LENGTH('LIQ_MermasStock', 'Item') IS NULL
    ALTER TABLE LIQ_MermasStock ADD Item VARCHAR(100) NOT NULL DEFAULT '0000';
IF COL_LENGTH('LIQ_MOV_SolicitudesDetalle', 'Item') IS NULL
    ALTER TABLE LIQ_MOV_SolicitudesDetalle ADD Item VARCHAR(100) NOT NULL DEFAULT '0000';
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'LIQ_NP_StockSnapshot') AND COL_LENGTH('LIQ_NP_StockSnapshot', 'Item') IS NULL
    ALTER TABLE LIQ_NP_StockSnapshot ADD Item VARCHAR(100) NOT NULL DEFAULT '0000';
IF COL_LENGTH('LIQ_REQ_Recepciones', 'Item') IS NULL
    ALTER TABLE LIQ_REQ_Recepciones ADD Item VARCHAR(100) NOT NULL DEFAULT '0000';
GO
